# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-12-18 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True, verbose_name='URL to shorten')),
                ('code', models.CharField(max_length=6, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Shortening Date')),
                ('username', models.CharField(blank=True, max_length=30, null=True)),
                ('nb_access', models.IntegerField(default=0, verbose_name='Number of access to the URL')),
            ],
        ),
    ]
